spring.main.banner-mode=off

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/billing

spring.jpa.hibernate.ddl-auto=update